// Shared helpers for viewing/downloading payment proof.
// - Offline payments: the uploaded slip image.
// - Online payments: a generated receipt (no image was uploaded).

export function downloadDataUrl(dataUrl, filename) {
  const a = document.createElement('a');
  a.href = dataUrl;
  a.download = filename || 'payment-proof.png';
  document.body.appendChild(a);
  a.click();
  a.remove();
}

// Draws a simple branded receipt to a canvas and downloads it as PNG.
export function downloadReceipt(fields, filename) {
  const W = 660, H = 480;
  const canvas = document.createElement('canvas');
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, W, H);

  // header
  ctx.fillStyle = '#3284c7';
  ctx.fillRect(0, 0, W, 76);
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 22px Arial, sans-serif';
  ctx.fillText(fields.title || 'Payment Receipt', 28, 46);
  const st = (fields.status || '').toUpperCase();
  if (st) {
    ctx.font = 'bold 14px Arial, sans-serif';
    ctx.fillText(st, W - 28 - ctx.measureText(st).width, 45);
  }

  const rows = [
    ['Receipt No', fields.receiptNo],
    ['Date & Time', fields.datetime],
    ['Student', fields.student],
    ['Fee', fields.fee],
    ['Class', fields.className],
    ['Method', fields.method],
    ['Reference', fields.ref],
  ].filter(r => r[1] != null && String(r[1]).trim() !== '' && String(r[1]) !== '—');

  let y = 122;
  rows.forEach(([k, v]) => {
    ctx.fillStyle = '#71717a'; ctx.font = '13px Arial, sans-serif';
    ctx.fillText(k, 28, y);
    ctx.fillStyle = '#18181b'; ctx.font = 'bold 15px Arial, sans-serif';
    ctx.fillText(String(v), 230, y);
    y += 40;
  });

  // amount block
  ctx.strokeStyle = '#e4e4e7';
  ctx.beginPath(); ctx.moveTo(28, y - 6); ctx.lineTo(W - 28, y - 6); ctx.stroke();
  ctx.fillStyle = '#71717a'; ctx.font = '13px Arial, sans-serif';
  ctx.fillText('Amount', 28, y + 30);
  ctx.fillStyle = '#3284c7'; ctx.font = 'bold 26px Arial, sans-serif';
  ctx.fillText(String(fields.amount || ''), 230, y + 34);

  // footer
  ctx.strokeStyle = '#e4e4e7';
  ctx.beginPath(); ctx.moveTo(28, H - 60); ctx.lineTo(W - 28, H - 60); ctx.stroke();
  ctx.fillStyle = '#a1a1aa'; ctx.font = '12px Arial, sans-serif';
  ctx.fillText('Generated by SmartEdz · system-generated receipt.', 28, H - 32);

  downloadDataUrl(canvas.toDataURL('image/png'), filename || 'receipt.png');
}